### ISSUE TITLE
TypeError: allCharacters[target].adjustRelationshipWith is not a function

### ISSUE THREAD

**Issue by jdm** [jdm/nanogenmo2019#11]
```
/Users/jdm/src/gen/gen.js:751
            ({actor, target}) => allCharacters[target].adjustRelationshipWith(actor, 0.6),
                                                       ^

TypeError: allCharacters[target].adjustRelationshipWith is not a function
    at Actions.actor (/Users/jdm/src/gen/gen.js:751:56)
    at Scene.generateAction (/Users/jdm/src/gen/gen.js:1275:24)
    at createScene (/Users/jdm/src/gen/gen.js:1352:15)
    at Object.<anonymous> (/Users/jdm/src/gen/gen.js:1374:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by jdm** [comment]
This was fixed.
