### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by jdm** [jdm/nanogenmo2019#12]
```
(node:72786) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at Character.adjustRelationshipWith (/Users/jdm/src/gen/gen.js:278:23)
    at async.actor.actor (/Users/jdm/src/gen/gen.js:858:56)
    at Scene.generateAction (/Users/jdm/src/gen/gen.js:1486:24)
    at async createScene (/Users/jdm/src/gen/gen.js:1564:9)
    at async create (/Users/jdm/src/gen/gen.js:1587:22)
(node:72786) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:72786) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jdm** [comment]
Fixed by d67e2e3.
